name: Run Python Script on Pull Request

on:
  pull_request:
    branches:
      - main # change this to your main branch

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      # check out the repositories
      - name: Checkout ta2-minmod-kg
        uses: actions/checkout@v4
        with:
          repository: DARPA-CRITICALMAAS/ta2-minmod-kg
          ref: main
          path: ta2-minmod-kg
      - name: Checkout ta2-minmod-data
        uses: actions/checkout@v4
        with:
          path: ta2-minmod-data

      # install dependencies
      - name: setup python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.11
      - name: install python dependencies
        run: |
          cd ta2-minmod-kg
          pip install -e .
      - name: get shacl validator
        run: |
          mkdir kgdata
          cd kgdata
          wget https://repo1.maven.org/maven2/org/topbraid/shacl/1.4.3/shacl-1.4.3-bin.zip
          unzip shacl-1.4.3-bin.zip
          rm shacl-1.4.3-bin.zip
      # get changed files
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"
      - name: run validator
        run: |
          echo ::group::Save changed files
          echo '${{ steps.files.outputs.all }}' >> kgdata/changed_files.json'
          echo ::endgroup::

          echo ::group::Run validator
          python -m minmodkg.validators ./ta2-minmod-data ./kgdata/validators ./kgdata/shacl-1.4.3/bin/shaclvalidate.sh ./kgdata/changed_files.json
          echo ::endgroup::
