name: Run Python Script on Pull Request

on:
  pull_request:
    branches:
      - main  # change this to your main branch

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository Data
        uses: actions/checkout@v3
        with:
          path: ta2-minmod-data

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: DARPA-CRITICALMAAS/ta2-minmod-kg
          ref: git-lfs-downnload-2
          path: ta2-minmod-kg

      - name: Print directory
        run:  |
          pwd
          ls

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # change this to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          full_path=$(pwd)
          cd_here="$(dirname "$full_path")/ta2-minmod-data/ta2-minmod-kg/validators/requirements.txt"
          pip install -r ${cd_here}  # change this if you have dependencies

      - name: Install tj-actions
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          since_last_remote_commit: false


      - name: List all changed files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          pwd
          ls
          for file in ${ALL_CHANGED_FILES}; do
            full_path=$(pwd)
            echo $full_path
            full_path_2=$full_path"/ta2-minmod-data/"$file
            echo $full_path_2
            echo "$file was changed"
            python_script_path="$(dirname "$full_path")/ta2-minmod-data/ta2-minmod-kg/validators/validate_schema_github_actions.py"
            cd_here="$(dirname "$full_path")/ta2-minmod-data/ta2-minmod-kg/"
            cd ${cd_here}
            git lfs pull
            echo "$python_script_path"
            TEMP_FILE=$(mktemp)
            ls
            python ${python_script_path} ${full_path_2} ${TEMP_FILE} ${cd_here}
          done


#            python validators/validate_schema_github_actions.py ${changed_file} ${TEMP_FILE} ${{ secrets.BEARER_TOKEN }} ${{ github.event.pull_request.head.ref }}
#      - id: files
#        with:
#          path: ta2-minmod-data
#          since_last_remote_commit: false
#        env:
#          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          pwd
#          ls
#          echo ${ALL_CHANGED_FILES}
#          for changed_file in ${ALL_CHANGED_FILES}; do
#            TEMP_FILE=$(mktemp)
#            echo $changed_file
#            echo $TEMP_FILE
#          done
#
